receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:8317
      http:
        endpoint: 0.0.0.0:8318
  zipkin:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  debug:

  zipkin:
    endpoint: http://telemetry-test-zipkin:9411/api/v2/spans
    format: proto

  otlp:
    endpoint: http://telemetry-test-jaeger:4317
    tls:
      insecure: true

  logging:
    verbosity: detailed

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [pprof, zpages, health_check]
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      exporters: [logging, debug, otlp, zipkin]
      processors: [batch]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, debug, prometheus]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging ]
