scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['telemetry-test-otel-collector:8889']
      - targets: ['telemetry-test-otel-collector:8888']
